/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author ivans
 */
public class inicioAdmin extends javax.swing.JFrame {

    int mousepX;
    int mousepY;
    public inicioAdmin() {
        initComponents();
        this.setLocationRelativeTo(null);
        login l = new login();
        lblUsuario.setText("Bienvenido "+l.nom);
        addCliente.hide();
        listarCliente.hide();
        addProfesional.hide();
        listarProfesional.hide();
        listarContratos.hide();
        agregarPago.hide();
        estadoPago.hide();
        planificacionCapacitacion.hide();
        lblAddCliente.hide();
        lblAddProfesional.hide();
        lblCargoExtra.hide();
        lblEstadoPago.hide();
        lblListCliente.hide();
        lblListContrato.hide();
        lblListProfesional.hide();
        lblPlanificacion.hide();
        setColor(panelInicio);
    }

    private void setColor(JPanel panel) {
        panel.setBackground(new Color(96, 95, 249));
    }

    private void resetColor(JPanel panel) {
        panel.setBackground(new Color(47, 46, 157));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        sidepane = new javax.swing.JPanel();
        panelContrato = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelProfesional = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panelCliente = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        panelPagos = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        panelActividades = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        panelInicio = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        Inicio = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        addProfesional = new javax.swing.JLabel();
        listarCliente = new javax.swing.JLabel();
        addCliente = new javax.swing.JLabel();
        listarProfesional = new javax.swing.JLabel();
        listarContratos = new javax.swing.JLabel();
        estadoPago = new javax.swing.JLabel();
        agregarPago = new javax.swing.JLabel();
        planificacionCapacitacion = new javax.swing.JLabel();
        lblAddCliente = new javax.swing.JLabel();
        lblAddProfesional = new javax.swing.JLabel();
        lblListCliente = new javax.swing.JLabel();
        lblListProfesional = new javax.swing.JLabel();
        lblListContrato = new javax.swing.JLabel();
        lblPlanificacion = new javax.swing.JLabel();
        lblEstadoPago = new javax.swing.JLabel();
        lblCargoExtra = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidepane.setBackground(new java.awt.Color(15, 14, 140));
        sidepane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelContrato.setBackground(new java.awt.Color(47, 46, 157));
        panelContrato.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelContrato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelContratoMousePressed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_contract_30px.png"))); // NOI18N

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Gestión Contrato ");

        javax.swing.GroupLayout panelContratoLayout = new javax.swing.GroupLayout(panelContrato);
        panelContrato.setLayout(panelContratoLayout);
        panelContratoLayout.setHorizontalGroup(
            panelContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContratoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );
        panelContratoLayout.setVerticalGroup(
            panelContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContratoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        sidepane.add(panelContrato, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 310, 50));

        panelProfesional.setBackground(new java.awt.Color(47, 46, 157));
        panelProfesional.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelProfesional.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelProfesionalMousePressed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_businessman_26px.png"))); // NOI18N

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Gestión Profesional ");

        javax.swing.GroupLayout panelProfesionalLayout = new javax.swing.GroupLayout(panelProfesional);
        panelProfesional.setLayout(panelProfesionalLayout);
        panelProfesionalLayout.setHorizontalGroup(
            panelProfesionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProfesionalLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );
        panelProfesionalLayout.setVerticalGroup(
            panelProfesionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProfesionalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        sidepane.add(panelProfesional, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, -1, 50));

        panelCliente.setBackground(new java.awt.Color(47, 46, 157));
        panelCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelClienteMousePressed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_client_company_32px.png"))); // NOI18N

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Gestión Cliente ");

        javax.swing.GroupLayout panelClienteLayout = new javax.swing.GroupLayout(panelCliente);
        panelCliente.setLayout(panelClienteLayout);
        panelClienteLayout.setHorizontalGroup(
            panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClienteLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );
        panelClienteLayout.setVerticalGroup(
            panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        sidepane.add(panelCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 310, 50));

        panelPagos.setBackground(new java.awt.Color(47, 46, 157));
        panelPagos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelPagos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelPagosMousePressed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_payment_history_32px.png"))); // NOI18N

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Gestión Pagos ");

        javax.swing.GroupLayout panelPagosLayout = new javax.swing.GroupLayout(panelPagos);
        panelPagos.setLayout(panelPagosLayout);
        panelPagosLayout.setHorizontalGroup(
            panelPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPagosLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );
        panelPagosLayout.setVerticalGroup(
            panelPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPagosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        sidepane.add(panelPagos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 310, 50));

        panelActividades.setBackground(new java.awt.Color(47, 46, 157));
        panelActividades.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelActividades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelActividadesMousePressed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_to_do_26px.png"))); // NOI18N

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Control Actividades");

        javax.swing.GroupLayout panelActividadesLayout = new javax.swing.GroupLayout(panelActividades);
        panelActividades.setLayout(panelActividadesLayout);
        panelActividadesLayout.setHorizontalGroup(
            panelActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelActividadesLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        panelActividadesLayout.setVerticalGroup(
            panelActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelActividadesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        sidepane.add(panelActividades, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 310, 50));
        sidepane.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 250, 20));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_no_entry_32px_1.png"))); // NOI18N
        sidepane.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 30, 40));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("No Mas Accidentes");
        sidepane.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 200, 20));

        panelInicio.setBackground(new java.awt.Color(47, 46, 157));
        panelInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelInicioMousePressed(evt);
            }
        });

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_home_32px.png"))); // NOI18N

        Inicio.setBackground(new java.awt.Color(255, 255, 255));
        Inicio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Inicio.setForeground(new java.awt.Color(204, 204, 204));
        Inicio.setText("Inicio");

        javax.swing.GroupLayout panelInicioLayout = new javax.swing.GroupLayout(panelInicio);
        panelInicio.setLayout(panelInicioLayout);
        panelInicioLayout.setHorizontalGroup(
            panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInicioLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );
        panelInicioLayout.setVerticalGroup(
            panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Inicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        sidepane.add(panelInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 310, 50));

        bg.add(sidepane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 600));

        jPanel1.setBackground(new java.awt.Color(96, 95, 249));
        jPanel1.setName(""); // NOI18N

        lblUsuario.setFont(new java.awt.Font("Franklin Gothic Book", 0, 36)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 830, 150));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel13.setText("X");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel13MousePressed(evt);
            }
        });
        bg.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 10, -1, 30));

        jLabel16.setBackground(new java.awt.Color(0, 0, 0));
        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_no_entry_32px_2.png"))); // NOI18N
        bg.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 30, 40));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setText("No Mas Accidentes");
        bg.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 200, 20));

        addProfesional.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addProfesional.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/69f041d8-194f-40b5-94c4-c504ea20d1b2.png"))); // NOI18N
        addProfesional.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addProfesional.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addProfesional.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addProfesionalMousePressed(evt);
            }
        });
        bg.add(addProfesional, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, 160, 160));

        listarCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        listarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/54e5ce28-c16f-4e2a-8682-4424e257fbbf.png"))); // NOI18N
        listarCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        listarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                listarClienteMousePressed(evt);
            }
        });
        bg.add(listarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 240, 160, 160));

        addCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/69f041d8-194f-40b5-94c4-c504ea20d1b2.png"))); // NOI18N
        addCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addClienteMouseClicked(evt);
            }
        });
        bg.add(addCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, 160, 160));

        listarProfesional.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        listarProfesional.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/54e5ce28-c16f-4e2a-8682-4424e257fbbf.png"))); // NOI18N
        listarProfesional.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        listarProfesional.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listarProfesional.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listarProfesionalMouseClicked(evt);
            }
        });
        bg.add(listarProfesional, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 240, 160, 160));

        listarContratos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        listarContratos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/54e5ce28-c16f-4e2a-8682-4424e257fbbf.png"))); // NOI18N
        listarContratos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        listarContratos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listarContratos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listarContratosMouseClicked(evt);
            }
        });
        bg.add(listarContratos, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 240, 160, 160));

        estadoPago.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        estadoPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_payment_history_80px.png"))); // NOI18N
        estadoPago.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        estadoPago.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        estadoPago.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                estadoPagoMouseClicked(evt);
            }
        });
        bg.add(estadoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, 160, 160));

        agregarPago.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        agregarPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/5170c35e-4e57-41dd-9e5f-9f478c77580d.png"))); // NOI18N
        agregarPago.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        agregarPago.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        agregarPago.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarPagoMouseClicked(evt);
            }
        });
        bg.add(agregarPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 240, 160, 160));

        planificacionCapacitacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        planificacionCapacitacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_calendar_100px_1.png"))); // NOI18N
        planificacionCapacitacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        planificacionCapacitacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        planificacionCapacitacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                planificacionCapacitacionMouseClicked(evt);
            }
        });
        bg.add(planificacionCapacitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 240, 160, 160));

        lblAddCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAddCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddCliente.setText("Agregar Cliente");
        bg.add(lblAddCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 400, 160, 20));

        lblAddProfesional.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAddProfesional.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddProfesional.setText("Agregar Profesional");
        bg.add(lblAddProfesional, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 400, 160, 20));

        lblListCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblListCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblListCliente.setText("Listar Cliente");
        bg.add(lblListCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 400, 150, 20));

        lblListProfesional.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblListProfesional.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblListProfesional.setText("Listar Profesional");
        bg.add(lblListProfesional, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 400, 150, 20));

        lblListContrato.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblListContrato.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblListContrato.setText("Listar Contratos");
        bg.add(lblListContrato, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 400, 150, 20));

        lblPlanificacion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPlanificacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlanificacion.setText("Planificación Capacitaciones ");
        bg.add(lblPlanificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 400, 210, 20));

        lblEstadoPago.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEstadoPago.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEstadoPago.setText("Estado Pago");
        bg.add(lblEstadoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 400, 160, 20));

        lblCargoExtra.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCargoExtra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCargoExtra.setText("Cargo Extra");
        bg.add(lblCargoExtra, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 400, 160, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int coordenadaX = evt.getXOnScreen();
        int coordenadaY = evt.getYOnScreen();
        this.setLocation(coordenadaX-mousepX, coordenadaY-mousepY);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        mousepX = evt.getX();
        mousepY = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void panelContratoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelContratoMousePressed
        addCliente.hide();
        listarCliente.hide();
        addProfesional.hide();
        listarProfesional.hide();
        listarContratos.show();
        agregarPago.hide();
        estadoPago.hide();
        planificacionCapacitacion.hide();
        lblAddCliente.hide();
        lblAddProfesional.hide();
        lblCargoExtra.hide();
        lblEstadoPago.hide();
        lblListCliente.hide();
        lblListContrato.show();
        lblListProfesional.hide();
        lblPlanificacion.hide();
        setColor(panelContrato);
        resetColor(panelCliente);
        resetColor(panelProfesional);
        resetColor(panelPagos);
        resetColor(panelActividades);
        resetColor(panelInicio);
    }//GEN-LAST:event_panelContratoMousePressed

    private void panelProfesionalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelProfesionalMousePressed
        addCliente.hide();
        addProfesional.show();
        listarCliente.hide();
        listarProfesional.show();
        listarContratos.hide();
        agregarPago.hide();
        estadoPago.hide();
        planificacionCapacitacion.hide();
        lblAddCliente.hide();
        lblAddProfesional.show();
        lblCargoExtra.hide();
        lblEstadoPago.hide();
        lblListCliente.hide();
        lblListContrato.hide();
        lblListProfesional.show();
        lblPlanificacion.hide();
        setColor(panelProfesional);
        resetColor(panelCliente);
        resetColor(panelContrato);
        resetColor(panelPagos);
        resetColor(panelActividades);
        resetColor(panelInicio);
    }//GEN-LAST:event_panelProfesionalMousePressed

    private void panelClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelClienteMousePressed
        addCliente.show();
        listarCliente.show();
        addProfesional.hide();
        listarProfesional.hide();
        listarContratos.hide();
        agregarPago.hide();
        estadoPago.hide();
        planificacionCapacitacion.hide();
        lblAddCliente.show();
        lblAddProfesional.hide();
        lblCargoExtra.hide();
        lblEstadoPago.hide();
        lblListCliente.show();
        lblListContrato.hide();
        lblListProfesional.hide();
        lblPlanificacion.hide();
        setColor(panelCliente);
        resetColor(panelProfesional);
        resetColor(panelContrato);
        resetColor(panelPagos);
        resetColor(panelActividades);
        resetColor(panelInicio);
    }//GEN-LAST:event_panelClienteMousePressed

    private void panelPagosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelPagosMousePressed
        addCliente.hide();
        listarCliente.hide();
        addProfesional.hide();
        listarProfesional.hide();
        listarContratos.hide();
        agregarPago.show();
        estadoPago.show();
        planificacionCapacitacion.hide();
        lblAddCliente.hide();
        lblAddProfesional.hide();
        lblCargoExtra.show();
        lblEstadoPago.show();
        lblListCliente.hide();
        lblListContrato.hide();
        lblListProfesional.hide();
        lblPlanificacion.hide();
        setColor(panelPagos);
        resetColor(panelCliente);
        resetColor(panelProfesional);
        resetColor(panelContrato);
        resetColor(panelActividades);
        resetColor(panelInicio);
    }//GEN-LAST:event_panelPagosMousePressed

    private void panelActividadesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelActividadesMousePressed
        listarProfesional.hide();
        listarContratos.hide();
        addCliente.hide();
        listarCliente.hide();
        addProfesional.hide();
        agregarPago.hide();
        estadoPago.hide();
        lblAddCliente.hide();
        lblAddProfesional.hide();
        lblCargoExtra.hide();
        lblEstadoPago.hide();
        lblListCliente.hide();
        lblListContrato.hide();
        lblListProfesional.hide();
        lblPlanificacion.show();
        planificacionCapacitacion.show();
        setColor(panelActividades);
        resetColor(panelCliente);
        resetColor(panelProfesional);
        resetColor(panelContrato);
        resetColor(panelPagos);
        resetColor(panelInicio);
    }//GEN-LAST:event_panelActividadesMousePressed

    private void panelInicioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelInicioMousePressed
        listarProfesional.hide();
        listarContratos.hide();
        addCliente.hide();
        listarCliente.hide();
        addProfesional.hide();
        agregarPago.hide();
        estadoPago.hide();
        lblAddCliente.hide();
        lblAddProfesional.hide();
        lblCargoExtra.hide();
        lblEstadoPago.hide();
        lblListCliente.hide();
        lblListContrato.hide();
        lblListProfesional.hide();
        lblPlanificacion.hide();
        planificacionCapacitacion.hide();
        setColor(panelInicio);
        resetColor(panelCliente);
        resetColor(panelProfesional);
        resetColor(panelContrato);
        resetColor(panelPagos);
        resetColor(panelActividades);
    }//GEN-LAST:event_panelInicioMousePressed

    private void jLabel13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MousePressed
        dispose();
        login lg = new login();
        lg.setVisible(true);
    }//GEN-LAST:event_jLabel13MousePressed

    private void addProfesionalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addProfesionalMousePressed
        agregarProfesional profesional = new agregarProfesional();
        profesional.setVisible(true);
    }//GEN-LAST:event_addProfesionalMousePressed

    private void listarClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listarClienteMousePressed
        listaUsuario lstU = new listaUsuario();
        lstU.setVisible(true);
    }//GEN-LAST:event_listarClienteMousePressed

    private void addClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addClienteMouseClicked
        agregarUsuario cliente = new agregarUsuario();
        cliente.setVisible(true);
    }//GEN-LAST:event_addClienteMouseClicked

    private void listarProfesionalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listarProfesionalMouseClicked
        listaProfesional lst = new listaProfesional();
        lst.setVisible(true);
    }//GEN-LAST:event_listarProfesionalMouseClicked

    private void listarContratosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listarContratosMouseClicked
        listarContratos lc = new listarContratos();
        lc.setVisible(true);
    }//GEN-LAST:event_listarContratosMouseClicked

    private void estadoPagoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estadoPagoMouseClicked
        estadoPago ep = new estadoPago();
        ep.setVisible(true);
    }//GEN-LAST:event_estadoPagoMouseClicked

    private void agregarPagoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarPagoMouseClicked
        agregarPago ap = new agregarPago();
        ap.setVisible(true);
    }//GEN-LAST:event_agregarPagoMouseClicked

    private void planificacionCapacitacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_planificacionCapacitacionMouseClicked
        planificacionCapacitacion pc = new planificacionCapacitacion();
        pc.setVisible(true);
    }//GEN-LAST:event_planificacionCapacitacionMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(inicioAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(inicioAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(inicioAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(inicioAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new inicioAdmin().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Inicio;
    private javax.swing.JLabel addCliente;
    private javax.swing.JLabel addProfesional;
    private javax.swing.JLabel agregarPago;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel estadoPago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAddCliente;
    private javax.swing.JLabel lblAddProfesional;
    private javax.swing.JLabel lblCargoExtra;
    private javax.swing.JLabel lblEstadoPago;
    private javax.swing.JLabel lblListCliente;
    private javax.swing.JLabel lblListContrato;
    private javax.swing.JLabel lblListProfesional;
    private javax.swing.JLabel lblPlanificacion;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel listarCliente;
    private javax.swing.JLabel listarContratos;
    private javax.swing.JLabel listarProfesional;
    private javax.swing.JPanel panelActividades;
    private javax.swing.JPanel panelCliente;
    private javax.swing.JPanel panelContrato;
    private javax.swing.JPanel panelInicio;
    private javax.swing.JPanel panelPagos;
    private javax.swing.JPanel panelProfesional;
    private javax.swing.JLabel planificacionCapacitacion;
    private javax.swing.JPanel sidepane;
    // End of variables declaration//GEN-END:variables
}
